/*
CONSULTA ALMACENADA EN LA BASE DE DATOS QUE SE UTILIZA COMO UNA TABLA VIRTUAL Y NO ALMACENA
SINO QUE UTILIZA ASOCIACIONES Y LOS DATOS DE LAS TABLAS ORIGINALES DE FORMA QUE SIEMPRE SE MANTIENE ACTUALIZADA
 */
CREATE VIEW entries_with_name AS
SELECT c.name, COUNT(e.id) AS 'NUMBER OF ENTRIES'
FROM categories c
INNER JOIN entries e ON e.category_id = c.id
GROUP BY category_id;
